# This is the base image for the dashboard app
FROM python:3.10-slim-bullseye

# Set working directory
WORKDIR /home

# Install dependencies
COPY requirements_dashboard.txt .
RUN python3 -m venv .venv
RUN .venv/bin/pip install -r requirements_dashboard.txt

# Copy files
COPY logo.jpeg .
COPY dashboard.py .
COPY ./src ./src
COPY ./metadata ./metadata

# Run dashboard app
CMD [ ".venv/bin/python3", "-m" , "streamlit", "run", "dashboard.py"]