FROM python:3.10-slim-bullseye

# Instructions to install dependencies and run enviroment
COPY requirements_full.txt .
RUN python3 -m venv .venv
RUN .venv/bin/pip install -r requirements_full.txt

# Instructions to copy the folder of the saved models, the source code and the metadata
COPY ./models ./models

COPY ./src ./src
COPY ./metadata ./metadata
COPY app.py .

# Instructions to run the server
CMD [ ".venv/bin/python3", "-m" , "flask", "run", "--host=0.0.0.0"]