FROM python:3.10-slim-bullseye

WORKDIR /home

COPY requirements_dashboard.txt .
RUN python3 -m venv .venv
RUN .venv/bin/pip install -r requirements_dashboard.txt

COPY dashboard.py .

CMD [ ".venv/bin/python3", "-m" , "streamlit", "run", "dashboard.py"]